"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Program = { id:string; name:string; slug:string; summary:string|null; status:"active"|"watching"|"archived"; cover_url:string|null; updated_at:string };
const blank = { id:"", name:"", slug:"", summary:"", status:"watching" as Program["status"], coverUrl:"" };
const slugify=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");

export default function ProgramManager({initialPrograms}:{initialPrograms:Program[]}){
  const [items,setItems]=useState(initialPrograms); const [form,setForm]=useState(blank); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
  function edit(p:Program){setForm({id:p.id,name:p.name,slug:p.slug,summary:p.summary??"",status:p.status,coverUrl:p.cover_url??""});setNotice("");window.scrollTo({top:0,behavior:"smooth"});}
  function fresh(){setForm(blank);setNotice("");}
  async function save(e:React.FormEvent){e.preventDefault(); const supabase=createClient(); if(!supabase)return; if(!form.name.trim())return setNotice("Nama program wajib diisi."); setBusy(true); const payload={name:form.name.trim(),slug:form.slug||slugify(form.name),summary:form.summary.trim()||null,status:form.status,cover_url:form.coverUrl.trim()||null,updated_at:new Date().toISOString()}; const r=form.id?await supabase.from("program_hubs").update(payload).eq("id",form.id).select().single():await supabase.from("program_hubs").insert(payload).select().single(); setBusy(false); if(r.error)return setNotice(r.error.message); const saved=r.data as Program; setItems(cur=>form.id?cur.map(x=>x.id===saved.id?saved:x):[saved,...cur]); setForm({id:saved.id,name:saved.name,slug:saved.slug,summary:saved.summary??"",status:saved.status,coverUrl:saved.cover_url??""}); setNotice("Program berhasil disimpan.");}
  async function remove(p:Program){if(!confirm(`Hapus program “${p.name}”?`))return; const supabase=createClient(); if(!supabase)return; const r=await supabase.from("program_hubs").delete().eq("id",p.id); if(r.error)return setNotice(r.error.message); setItems(cur=>cur.filter(x=>x.id!==p.id)); if(form.id===p.id)fresh();}
  return <div className="manager-page"><header className="manager-top"><div><a href="/admin">← Dashboard</a><span>Program Hub</span><h1>Kelola program.</h1><p>Atur program dan isu kebijakan yang dipantau Opinimiu. Perubahan langsung tampil di halaman Program.</p></div><a className="cms-secondary" href="/program" target="_blank">Lihat halaman publik ↗</a></header><div className="manager-grid"><form className="cms-card manager-form" onSubmit={save}><div className="cms-card-head"><div><span>{form.id?"Edit":"Baru"}</span><h2>{form.id?"Edit program":"Tambah program"}</h2></div><button type="button" className="cms-secondary" onClick={fresh}>Kosongkan</button></div><label>Nama<input value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:form.id?form.slug:slugify(e.target.value)})} required /></label><label>Slug<input value={form.slug} onChange={e=>setForm({...form,slug:slugify(e.target.value)})}/></label><label>Ringkasan<textarea rows={5} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Program["status"]})}><option value="watching">Dalam pantauan</option><option value="active">Aktif</option><option value="archived">Arsip</option></select></label><label>URL cover<input type="url" value={form.coverUrl} onChange={e=>setForm({...form,coverUrl:e.target.value})}/></label><button className="cms-primary" disabled={busy}>{busy?"Menyimpan...":"Simpan program"}</button>{notice&&<div className="cms-notice">{notice}</div>}</form><section className="cms-card"><div className="cms-card-head"><div><span>Database</span><h2>{items.length} program</h2></div></div><div className="manager-list">{items.map(p=><article key={p.id}><div><span className={`status-pill status-${p.status}`}>{p.status}</span><h3>{p.name}</h3><p>{p.summary||"Belum ada ringkasan."}</p></div><div className="row-actions"><button onClick={()=>edit(p)}>Edit</button><button className="danger" onClick={()=>remove(p)}>Hapus</button></div></article>)}</div></section></div></div>;
}
